version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=https://auth-service-production-aabc.up.railway.app
      - RAILWAY_ENVIRONMENT=true
      - LOG_LEVEL=INFO
    depends_on:
      - auth-service
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    build:
      context: ./service/auth-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RAILWAY_ENVIRONMENT=true
      - LOG_LEVEL=INFO
      - GATEWAY_URL=https://gateway-production-be21.up.railway.app
      - HTTP_TIMEOUT=30
      - HTTP_MAX_CONNECTIONS=100
      - HTTP_MAX_KEEPALIVE=20
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge 