version: '3.8'

services:
  # Gateway 서비스
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - RAILWAY_ENVIRONMENT=true
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - auth-service
    networks:
      - app-network

  # Auth Service
  auth-service:
    build: ./service/auth-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - RAILWAY_ENVIRONMENT=true
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/educated
    depends_on:
      - postgres
    networks:
      - app-network

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=educated
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 